name: Build and deploy to gh-pages

on:
    push:
        branches: ['master']

jobs:
    gh-pages-build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Checkout branch
              uses: actions/checkout@v2
              
            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Build App
              run: yarn build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GH_TOKEN }}
                public_dir: ./docs
